### ISSUE TITLE
STORAGE undefined

### ISSUE THREAD

**Issue by livnev** [dapphub/klab#128]
In any `klab debug` proof, in the `STORAGE` block in the `evm` view I just see:

```
STORAGE                                                                                                                                                        
undefined
```

Meanwhile, the proof goes through without any problems.

I'm experiencing this issue on a fresh install of `klab` on a NixOS machine, and unable to reproduce it on my debian machine. @MrChico is also not experiencing it.

**Comment by t4sk** [comment]
@livnev I also see it when i build and run a docker image

**Comment by MrChico** [comment]
@t4sk, that example actually does not have storage defined, so this is not an issue

**Comment by t4sk** [comment]
@MrChico thanks for the explanation.
