### ISSUE TITLE
resolve "passing" and "succeeding" naming confusion

### ISSUE THREAD

**Issue by livnev** [dapphub/klab#158]
Currently `pass` and `passing` are words that are used to both describe a non-reverting case of an `act` spec and also when `kprove` has succeeded in proving a reachability rule. This is confusing.

**Comment by MrChico** [comment]
I think we have decided on `ACCEPT` vs. `REJECT` for how kprove may react to a spec

**Comment by livnev** [comment]
@MrChico I'm happy with that: the green/red status box in the bottom right of `klab debug` needs to be updated with that.

**Comment by mhhf** [comment]
i try to use `accept` and `reject` everywhere now, if you guys find something where this should change - reopen plz
