### ISSUE TITLE
sloppy Int stripping

### ISSUE THREAD

**Issue by livnev** [dapphub/klab#35]
Stripping out the string `Int` has sloppy results when dealing with symbols that have `Int` as a substring, such as in this example:

![klabbug](https://user-images.githubusercontent.com/3964494/44281429-0a64cc80-a258-11e8-8eae-a8b4812a3e6c.png)

where `sgnerp` is not the name of a function, and should instead be `sgnInterp`.

**Comment by mhhf** [comment]
solved with the newest dev
