### ISSUE TITLE
Feature:  klab build: balance field

### ISSUE THREAD

**Issue by livnev** [dapphub/klab#39]
Add a `balance Acct` field to the specification language, for reasoning about account (ETH) balances. For example

```
...
balance Guy
     Bal_guy => Bal_guy + wad
...
```

should compile to something like:
```
...
          <accounts>
            <account multiplicity="*" type="Map">
              <acctID>  Guy </acctID>
              <balance> Bal_guy => Bal_guy + wad </balance>
               ...
            </account>
          </accounts>
...
```

At the same time it would be useful to add `<value> VALUE </value>` to the "template".

**Comment by mhhf** [comment]
implemented in the new web branch
