### ISSUE TITLE
Show lemmas in r view

### ISSUE THREAD

**Issue by asymmetric** [dapphub/klab#405]
It seems the `r` view only shows rules defined in the evm-semantics, and not the ones we provide in e.g. `lemmas.k.md` files.

Investigate why, and how hard it is to change.

**Comment by MrChico** [comment]
It doesn't show `[function]`s, I'm afraid. That would require more instrumentalization of k to dump I believe

**Comment by mhhf** [comment]
thats quite impossible, k doesn't expose those informations
