### ISSUE TITLE
klab build: add preconditions for callable addresses

### ISSUE THREAD

**Issue by livnev** [dapphub/klab#49]
When `klab build` processes addresses that are going to be called (i.e. ones that have been labelled with an implementation alias), it should add some more preconditions to the spec: for example if it sees `Vat : address VatLike`, it should add the following:
```
...
  andBool #rangeAddress(Vat)
  andBool #notPrecompileAddress(Vat)
  andBool ACCT_ID =/=Int Vat
...
```
Note that the 2nd one should say `#notPrecompileAddress` (as not `#rangeNotPrecompileAddress` as we used before) since I want to switch to the former.

**Comment by mhhf** [comment]
fixed in the web branch
